function [ output_args ] = smallReconstructionRegionPlot(fig_handle, scatter_pos,scatter_buffer,label)

scatter_box=[];
for i=-1:2:1
    for j=-1:2:1
        for k=-1:2:1
            scatter_box=cat(1,scatter_box,...
                [scatter_pos(1)-i*scatter_buffer, ...
                scatter_pos(2)+j*scatter_buffer,...
                scatter_pos(3)+k*scatter_buffer]);
        end
    end
end
figure(fig_handle)
scatter_box=sortrows(scatter_box,[3,2,1]);

for m=1:length(scatter_box)/2
    plot3([scatter_box(m,1);scatter_box(m+4,1)],...
        [scatter_box(m,2);scatter_box(m+4,2)],...
        [scatter_box(m,3);scatter_box(m+4,3)],...
        'b'...
        )
end


scatter_box(1:4,:)=sortrows(scatter_box(1:4,:),2);
scatter_box(3:4,:)=sortrows(scatter_box(3:4,:),-1);

scatter_box(5:8,:)=sortrows(scatter_box(5:8,:),2);
scatter_box(7:8,:)=sortrows(scatter_box(7:8,:),-1);

scatter3(scatter_box(:,1),...
    scatter_box(:,2),...
    scatter_box(:,3)...
    ,'r')

plot3([scatter_box(1:4,1);scatter_box(1,1)],...
    [scatter_box(1:4,2);scatter_box(1,2)],...
    [scatter_box(1:4,3);scatter_box(1,3)],...
    'b'...
    );

plot3([scatter_box(5:8,1);scatter_box(5,1)],...
    [scatter_box(5:8,2);scatter_box(5,2)],...
    [scatter_box(5:8,3);scatter_box(5,3)],...
    'b'...
    );

text(scatter_pos(1)+1.5*scatter_buffer,...
    scatter_pos(2)+1.5*scatter_buffer,...
    scatter_pos(3)+1.5*scatter_buffer,...
    label,...
    'FontSize',14,...
    'Color','b'...
    );

end

